import { db } from './db';
import * as schema from './db/schema';

type OutreachChannel = 'email' | 'phone' | 'linkedin' | 'whatsapp' | 'in_person';

export async function createAutoReminder(
  businessId: string,
  channel: OutreachChannel,
  outcome?: string,
) {
  let daysUntilReminder = 3;
  let reminderType: 'follow_up' | 'call' | 'meeting_prep' | 'check_in' = 'follow_up';
  let title = 'Follow-up';

  if (channel === 'email') {
    daysUntilReminder = 3;
    title = 'Email follow-up';
  } else if (channel === 'phone') {
    daysUntilReminder = 2;
    reminderType = 'call';
    title = 'Terugbellen';
  } else if (channel === 'linkedin') {
    daysUntilReminder = 4;
    title = 'LinkedIn follow-up';
  }

  if (outcome?.toLowerCase().includes('interested') || outcome?.toLowerCase().includes('geïnteresseerd')) {
    daysUntilReminder = 1;
    reminderType = 'meeting_prep';
    title = 'Meeting inplannen — geïnteresseerd';
  }

  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + daysUntilReminder);

  await db.insert(schema.reminders).values({
    businessId,
    type: reminderType,
    title,
    description: `Auto-gegenereerd na ${channel} outreach`,
    dueDate,
    autoGenerated: true,
  });
}

export async function createProposalReminder(businessId: string) {
  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + 5);

  await db.insert(schema.reminders).values({
    businessId,
    type: 'follow_up',
    title: 'Offerte opvolgen',
    description: 'Auto-gegenereerd na versturen voorstel',
    dueDate,
    autoGenerated: true,
  });
}
