import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { eq } from 'drizzle-orm';
import { db } from '@/lib/db';
import * as schema from '@/lib/db/schema';
import { isValidSession } from '@/lib/auth';

const acceptSchema = z.object({
  suggestedChannel: z.string(),
  suggestedDays: z.number().int().min(1).max(30),
  draftMessage: z.string(),
  businessId: z.string().uuid(),
  suggestedAction: z.string().optional(),
});

interface RouteParams {
  params: Promise<{ id: string }>;
}

export async function POST(request: NextRequest, { params }: RouteParams) {
  await params; // consume params

  if (!isValidSession(request)) {
    return NextResponse.json({ error: 'Niet geautoriseerd' }, { status: 401 });
  }

  try {
    const body = await request.json();
    const parsed = acceptSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: 'Validatie mislukt', details: parsed.error.flatten() }, { status: 400 });
    }

    const { suggestedDays, draftMessage, businessId, suggestedAction } = parsed.data;
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + suggestedDays);

    // Maak reminder aan
    await db.insert(schema.reminders).values({
      businessId,
      type: 'follow_up',
      title: suggestedAction ?? 'AI follow-up suggestie',
      description: `AI-gegenereerde follow-up suggestie`,
      dueDate,
      suggestedMessage: draftMessage,
      autoGenerated: true,
    });

    // Update pipeline nextFollowUpAt
    await db
      .update(schema.leadPipeline)
      .set({
        nextFollowUpAt: dueDate,
        updatedAt: new Date(),
      })
      .where(eq(schema.leadPipeline.businessId, businessId));

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Accept follow-up error:', error);
    return NextResponse.json({ error: 'Interne serverfout' }, { status: 500 });
  }
}
