"use client";

import { useState, useEffect } from "react";
import { Check, X, Clock, Bell } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/utils";

interface ReminderEntry {
  reminder: {
    id: string;
    type: string;
    title: string;
    description: string | null;
    dueDate: string;
    status: string;
    autoGenerated: boolean;
  };
  business: {
    id: string;
    name: string;
  };
}

export function ReminderList() {
  const [reminders, setReminders] = useState<ReminderEntry[]>([]);
  const [loading, setLoading] = useState(true);

  async function fetchReminders() {
    try {
      const res = await fetch("/api/reminders?status=pending");
      const data = await res.json();
      setReminders(data);
    } catch {
      setReminders([]);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    fetchReminders();
  }, []);

  async function handleAction(id: string, status: "completed" | "skipped") {
    try {
      await fetch(`/api/reminders/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status }),
      });
      setReminders((prev) => prev.filter((r) => r.reminder.id !== id));
    } catch {
      // silently fail
    }
  }

  if (loading) return <p className="text-sm text-muted">Laden...</p>;
  if (reminders.length === 0) return <p className="text-sm text-muted">Geen openstaande reminders</p>;

  const now = new Date();

  return (
    <div className="space-y-3">
      {reminders.map(({ reminder, business }) => {
        const isOverdue = new Date(reminder.dueDate) < now;
        return (
          <div
            key={reminder.id}
            className={
              "flex items-start gap-3 p-3 rounded-lg border " +
              (isOverdue ? "border-red-200 bg-red-50/50" : "border-card-border bg-white")
            }
          >
            <Bell className={"h-4 w-4 mt-0.5 shrink-0 " + (isOverdue ? "text-red-500" : "text-accent")} />
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium">{reminder.title}</p>
              <p className="text-xs text-muted">{business.name}</p>
              {reminder.description && (
                <p className="text-xs text-muted mt-0.5">{reminder.description}</p>
              )}
              <div className="flex items-center gap-1 mt-1">
                <Clock className="h-3 w-3 text-muted" />
                <span className={"text-xs " + (isOverdue ? "text-red-600 font-medium" : "text-muted")}>
                  {formatDate(reminder.dueDate)}
                  {isOverdue && " — Verlopen!"}
                </span>
              </div>
            </div>
            <div className="flex items-center gap-1">
              <button
                onClick={() => handleAction(reminder.id, "completed")}
                className="p-1.5 rounded-md hover:bg-green-100 text-green-600 transition-colors"
                title="Voltooid"
              >
                <Check className="h-4 w-4" />
              </button>
              <button
                onClick={() => handleAction(reminder.id, "skipped")}
                className="p-1.5 rounded-md hover:bg-gray-100 text-muted transition-colors"
                title="Overslaan"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>
        );
      })}
    </div>
  );
}
